# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]
    paths:
    - '.github/workflows/deploy_pages.yml'
    - 'docs/**'
    - 'include/**'
    - 'README.md'
    - 'test/include/**'
    - 'test/src/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Setup Pages
        uses: actions/configure-pages@f156874f8191504dae5b037505266ed5dda6c382 # v3.0.6

      - name: Checkout Doxygen
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          repository: doxygen/doxygen
          ref: c2fe5c3e4986974eb2a97608b24086683502f07f # v1.9.8
          path: doxygen

      - name: Install Basic Dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake graphviz

      - name: Install Doxygen
        working-directory: doxygen
        run: |
          mkdir build
          cd build
          cmake -G "Unix Makefiles" ..
          make
          sudo make install

      - name: Prepare the documentation
        run: |
          cmake -B build -D BUILD_TESTING=OFF -D BUILD_EXAMPLES=OFF

      - name: Generate the documentation
        run: doxygen docs/Doxyfile
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@a753861a5debcf57bf8b404356158c8e1e33150c # v2.0.0
        with:
          # Upload docs/html
          path: 'docs/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@9dbe3824824f8a1377b8e298bafde1a50ede43e5 # v2.0.4
