name: Doxygen

on:
  pull_request:
    paths:
    - '.github/workflows/doxygen.yml'
    - 'docs/**'
    - 'include/**'
    - 'README.md'
    - 'test/include/**'
    - 'test/src/**'
  push:
    branches:
    - master
    paths:
    - '.github/workflows/doxygen.yml'
    - 'docs/**'
    - 'include/**'
    - 'README.md'
    - 'test/include/**'
    - 'test/src/**'

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:

  check-errors-in-the-documentation:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout <T>LAPACK
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

    - name: Checkout Doxygen
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        repository: doxygen/doxygen
        ref: c2fe5c3e4986974eb2a97608b24086683502f07f # v1.9.8
        path: doxygen

    - name: Install Basic Dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake graphviz

    - name: Install Doxygen
      working-directory: doxygen
      run: |
        mkdir build
        cd build
        cmake -G "Unix Makefiles" ..
        make
        sudo make install

    - name: Prepare the documentation
      run: |
        cmake -B build -D BUILD_TESTING=OFF -D BUILD_EXAMPLES=OFF

    - name: Generate the documentation
      run: doxygen docs/Doxyfile

    - name: Check for errors in the documentation
      run: |
        if [[ $(wc -l < docs/doxygen_warnings.log) -gt 1 ]]; then
          echo "There are errors in the documentation. Please, check the file docs/doxygen_warnings.log"
          ls -l docs/doxygen_warnings.log
          cat docs/doxygen_warnings.log | head -n 20
          exit 1
        fi